// Generated from migration-applied PostgreSQL catalog by pnpm db:types. Do not edit.
export type Json = string | number | boolean | null | { [key:string]: Json | undefined } | Json[];
export type Database={public:{Tables:{assignments: { Row: {id: string;tutor_id: string;student_id: string;term_id: string;starts_on: string;ends_on: string | null;end_reason: string | null;site: string;usual_days: string;usual_times: string;version: number}; Insert: {id?: string;tutor_id: string;student_id: string;term_id: string;starts_on: string;ends_on?: string | null;end_reason?: string | null;site?: string;usual_days?: string;usual_times?: string;version?: number}; Update: Partial<Database['public']['Tables']['assignments']['Insert']>; Relationships: [] };
attendance_events: { Row: {id: string;assignment_id: string;occurred_on: string;kind: string;duration_minutes: number;request_id: string;creation_payload: Json;created_by: string;updated_by: string;created_at: string;updated_at: string;version: number;voided_at: string | null;voided_by: string | null;void_reason: string | null}; Insert: {id?: string;assignment_id: string;occurred_on: string;kind: string;duration_minutes: number;request_id: string;creation_payload: Json;created_by: string;updated_by: string;created_at?: string;updated_at?: string;version?: number;voided_at?: string | null;voided_by?: string | null;void_reason?: string | null}; Update: Partial<Database['public']['Tables']['attendance_events']['Insert']>; Relationships: [] };
goal_types: { Row: {id: string;category: string;label: string;display_order: number;source_asterisk: boolean}; Insert: {id: string;category: string;label: string;display_order: number;source_asterisk?: boolean}; Update: Partial<Database['public']['Tables']['goal_types']['Insert']>; Relationships: [] };
memberships: { Row: {user_id: string;display_name: string;role: string;status: string}; Insert: {user_id: string;display_name: string;role?: string;status?: string}; Update: Partial<Database['public']['Tables']['memberships']['Insert']>; Relationships: [] };
student_achievements: { Row: {id: string;student_id: string;term_id: string;goal_type_id: string | null;custom_label: string | null;attained_on: string;recorded_by: string;created_at: string;updated_at: string;version: number;voided_at: string | null;voided_by: string | null;void_reason: string | null}; Insert: {id?: string;student_id: string;term_id: string;goal_type_id?: string | null;custom_label?: string | null;attained_on: string;recorded_by: string;created_at?: string;updated_at?: string;version?: number;voided_at?: string | null;voided_by?: string | null;void_reason?: string | null}; Update: Partial<Database['public']['Tables']['student_achievements']['Insert']>; Relationships: [] };
students: { Row: {id: string;display_name: string;created_at: string}; Insert: {id?: string;display_name: string;created_at?: string}; Update: Partial<Database['public']['Tables']['students']['Insert']>; Relationships: [] };
terms: { Row: {id: string;name: string;starts_on: string;ends_on: string}; Insert: {id?: string;name: string;starts_on: string;ends_on: string}; Update: Partial<Database['public']['Tables']['terms']['Insert']>; Relationships: [] }};Views:Record<string,never>;Functions:{achievement_report:{Args:{p:Json};Returns:Json};attendance_report:{Args:{p:Json};Returns:Json};create_attendance:{Args:{p:Json};Returns:Json};edit_attendance:{Args:{p:Json};Returns:Json};save_achievement:{Args:{p:Json};Returns:Json};save_assignment:{Args:{p:Json};Returns:Json};save_student:{Args:{p:Json};Returns:Json};set_membership:{Args:{p:Json};Returns:Json};workspace:{Args:Record<string,never>;Returns:Json}};Enums:Record<string,never>;CompositeTypes:Record<string,never>}};
